apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservationmgmt
  labels:
    app: reservationmgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservationmgmt
  template:
    metadata:
      labels:
        app: reservationmgmt
    spec:
      containers:
        - name: reservationmgmt
          image: username/reservationmgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
