apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservationhist
  labels:
    app: reservationhist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservationhist
  template:
    metadata:
      labels:
        app: reservationhist
    spec:
      containers:
        - name: reservationhist
          image: username/reservationhist:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
