---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedulemgmt
  labels:
    app: schedulemgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedulemgmt
  template:
    metadata:
      labels:
        app: schedulemgmt
    spec:
      containers:
        - name: schedulemgmt
          image: username/schedulemgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customermgmt
  labels:
    app: customermgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermgmt
  template:
    metadata:
      labels:
        app: customermgmt
    spec:
      containers:
        - name: customermgmt
          image: username/customermgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservationmgmt
  labels:
    app: reservationmgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservationmgmt
  template:
    metadata:
      labels:
        app: reservationmgmt
    spec:
      containers:
        - name: reservationmgmt
          image: username/reservationmgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notimgmt
  labels:
    app: notimgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notimgmt
  template:
    metadata:
      labels:
        app: notimgmt
    spec:
      containers:
        - name: notimgmt
          image: username/notimgmt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservationhist
  labels:
    app: reservationhist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservationhist
  template:
    metadata:
      labels:
        app: reservationhist
    spec:
      containers:
        - name: reservationhist
          image: username/reservationhist:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: schedulemgmt
  labels:
    app: schedulemgmt
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: schedulemgmt


---


apiVersion: v1
kind: Service
metadata:
  name: customermgmt
  labels:
    app: customermgmt
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customermgmt


---


apiVersion: v1
kind: Service
metadata:
  name: reservationmgmt
  labels:
    app: reservationmgmt
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservationmgmt


---


apiVersion: v1
kind: Service
metadata:
  name: notimgmt
  labels:
    app: notimgmt
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: notimgmt


---


apiVersion: v1
kind: Service
metadata:
  name: reservationhist
  labels:
    app: reservationhist
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservationhist

